backend/.gitignore
backend/utils/supabase.js
frontend/.gitignore
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/BlankPage.tsx
frontend/src/components/SuccessPage.tsx
frontend/src/components/auth/LoginPage.tsx
frontend/src/components/auth/RegisterPage.tsx
frontend/src/components/buttons/Button.tsx
frontend/src/components/navigation_pages/OnboardingPage.tsx
frontend/src/components/routing/router.tsx
frontend/src/main.tsx
frontend/src/utils/supabase.tsx

Adds Login and SignUp pages with email confirmation
Initializes Google login acceptance (currently frameworked but not functional due to Supabase requiring Google Workspaces authourization)

Initial auth routes setup

---

backend/package-lock.json
frontend/eslint.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/ProjectCard.tsx
frontend/src/components/ui/badge.tsx
frontend/src/components/ui/button.tsx
frontend/src/components/ui/card.tsx
frontend/src/components/ui/index.ts
frontend/src/components/ui/input.tsx
frontend/src/components/ui/label.tsx
frontend/src/components/ui/select.tsx
frontend/src/styles/index.css
frontend/tsconfig.eslint.json

I added the card component, called it ProjectCard. This component will be for both the SessionPage & ExplorePage project card.
currently it doesn't have the data for the card to show content. It needs props to be passed to it.
The onClick() needs to change a useState to be passed back up to parent to change view. (not yet implemented)

Card component

---

frontend/index.html
frontend/src/App.tsx
frontend/src/components/NavigationPage.tsx
frontend/src/components/auth/LoginPage.tsx
frontend/src/components/auth/RegisterPage.tsx

fixes "vite" placeholder title on index.html

Fixes index html

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/navigation_pages/Settings.tsx
frontend/src/components/ui/form.tsx
frontend/src/utils/formSchemas.ts
frontend/src/utils/supabase.tsx

Implemented Settings page
Included the ability to update the user's username, bio and change their preference for viewing mature content.
Users are able to save their profile settings to the database and the values settings will get populated on the settings page when the user returns.

Implemented Settings Page with form validation

---

frontend/src/components/navigation_pages/OpenSessionsPage.tsx
frontend/src/components/navigation_pages/ProjectsPage.tsx
frontend/src/components/navigation_pages/Settings.tsx

Fixed data error when receiving data from the database server.
Removed log messages.

fix: clean up code & fix server data accessing

---

.vscode/settings.json
frontend/src/App.tsx
frontend/src/components/Header.tsx
frontend/src/components/ProjectCard.tsx
frontend/src/components/SessionCard.tsx
frontend/src/components/SnippetSkeleton.tsx
frontend/src/components/navigation_pages/LandingPage.tsx
frontend/src/components/navigation_pages/OpenSessionsPage.tsx
frontend/src/components/navigation_pages/ReadingPage.tsx
frontend/src/components/routing/router.tsx
frontend/src/components/ui/skeleton.tsx
frontend/src/components/writing_pages/CreateSessionPage.tsx
frontend/src/components/writing_pages/WritingEditor.tsx
frontend/src/main.tsx
frontend/src/types/global.d.ts
frontend/src/utils/supabase.tsx

Adds the core writing component with round-robin functionality. 
adds ShadCN components and human readable timestamps via date-fns (https://date-fns.org/)
NPM install required after merging.

Creates writing component template

---

frontend/src/components/SessionCard.tsx
frontend/src/components/auth/RegisterPage.tsx
frontend/src/components/writing_pages/WritingEditor.tsx
frontend/src/utils/supabase.tsx

Reverts Team-NekoNyan/inkprov#15

Revert "Minor changes to writing page"

---

frontend/src/App.tsx
frontend/src/components/Footer.tsx
frontend/src/components/GenreFilter.tsx
frontend/src/components/Header.tsx
frontend/src/components/SearchBar.tsx
frontend/src/components/SessionCard.tsx
frontend/src/components/auth/LoginPage.tsx
frontend/src/components/auth/RegisterPage.tsx
frontend/src/components/navigation_pages/LandingPage.tsx
frontend/src/components/navigation_pages/OpenSessionsPage.tsx
frontend/src/components/navigation_pages/ProjectsPage.tsx
frontend/src/components/navigation_pages/Settings.tsx
frontend/src/components/routing/router.tsx
frontend/src/components/ui/form.tsx
frontend/src/components/writing_pages/CreateSessionPage.tsx
frontend/src/contexts/AuthContext.tsx
frontend/src/styles/App.css
frontend/src/styles/index.css

Fixed some ui and layout bugs.
Some styles and names have been updated to feel more stylized.
Functionality has remained unchanged.

fix: Fixed display bugs and update styles to be more dynamic.

---

frontend/package-lock.json
frontend/src/components/ProjectCard.tsx
frontend/src/components/navigation_pages/ProjectsPage.tsx
frontend/src/components/navigation_pages/ReadingPage.tsx
frontend/src/types/global.d.ts
frontend/src/utils/supabase.tsx

Project cards now properly displaying and can now see if the current user contributed to a completed project or not => but it is not well placed on the card nor is it styled.

fix: fix project cards to display

---

frontend/package-lock.json
frontend/src/components/SessionCard.tsx
frontend/src/components/auth/AuthCallback.tsx
frontend/src/components/auth/LoginPage.tsx
frontend/src/components/auth/RegisterPage.tsx
frontend/src/components/navigation_pages/OpenSessionsPage.tsx
frontend/src/components/navigation_pages/Settings.tsx
frontend/src/components/routing/router.tsx
frontend/src/components/writing_pages/CreateSessionPage.tsx
frontend/src/utils/supabase.tsx

Users should now be able to log in with Google oAuth

Enables google login support

---

frontend/src/components/GenreFilter.tsx
frontend/src/components/ProjectCard.tsx
frontend/src/styles/index.css

Added all the genre to the filter and color coded them. Have it hard coded , which I think is best to keep this way as its instant and we an change anytime, to reflect database. Unless we end up with huge list of genre, like sub genre, then maybe we would fetch that.

Genre filter update

---

backend/server.js
frontend/src/components/ProjectCard.tsx
frontend/src/components/SessionCard.tsx
frontend/src/components/navigation_pages/LandingPage.tsx
frontend/src/components/navigation_pages/Settings.tsx
frontend/src/components/routing/router.tsx
frontend/src/components/user/RewardTrophiesPage.tsx
frontend/src/components/writing_pages/WritingEditor.tsx
frontend/src/utils/supabase.tsx

[render preview] Fixes client side routing

---

backend/.gitignore
frontend/src/components/navigation_pages/Settings.tsx
frontend/src/utils/formSchemas.ts

Adds character count, validation, and editable to Zod fields on the profile page

FEAT: zod field fixes

---

.cursor/rules/comment-handling.mdc
frontend/package-lock.json
frontend/package.json
frontend/src/components/Footer.tsx
frontend/src/components/Header.tsx
frontend/src/components/navigation_pages/LandingPage.tsx
frontend/src/components/navigation_pages/OnboardingPage.tsx
frontend/src/components/navigation_pages/Profile.tsx
frontend/src/components/navigation_pages/ReadingPage.tsx
frontend/src/components/navigation_pages/Settings.tsx
frontend/src/components/routing/router.tsx
frontend/src/components/ui/index.ts
frontend/src/components/ui/tooltip.tsx
frontend/src/components/user/RewardTrophiesPage.tsx
frontend/src/components/writing_pages/CreateSessionPage.tsx
frontend/src/components/writing_pages/WritingEditor.tsx
frontend/src/utils/supabase.tsx
supabase_migration.sql

fixes the header's persistence, background color, and centering

Fixes header persistance

---

frontend/src/components/Footer.tsx
frontend/src/components/routing/router.tsx

unpins the footer while preserving styling

Fixes footer position and styling

---

frontend/src/components/Footer.tsx
frontend/src/components/Header.tsx

corrects and enhances previous fix for header positioning

Visual centering header elements

---

backend/aiAgent/aiChat.js
backend/server.js
backend/utils/contentModeration.js
backend/utils/openAIClient.js
frontend/src/components/navigation_pages/Settings.tsx
frontend/src/components/writing_pages/CreateSessionPage.tsx
frontend/src/components/writing_pages/WritingEditor.tsx

Implemented Content Moderation for text fields that accepts user input.
Moderation currently in use is Open AI Omni Moderation Model.

feat: Implement AI Content Moderation

---

frontend/index.html
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/Footer.tsx
frontend/src/components/GenreFilter.tsx
frontend/src/components/Header.tsx
frontend/src/components/ProjectCard.tsx
frontend/src/components/SearchBar.tsx
frontend/src/components/SessionCard.tsx
frontend/src/components/auth/LoginPage.tsx
frontend/src/components/auth/RegisterPage.tsx
frontend/src/components/navigation_pages/LandingPage.tsx
frontend/src/components/navigation_pages/OpenSessionsPage.tsx
frontend/src/components/navigation_pages/ProjectsPage.tsx
frontend/src/components/navigation_pages/ReadingPage.tsx
frontend/src/components/routing/router.tsx
frontend/src/components/ui/dropdown-menu.tsx
frontend/src/components/ui/sheet.tsx
frontend/src/components/writing_pages/CreateSessionPage.tsx
frontend/src/components/writing_pages/WritingEditor.tsx
frontend/src/styles/App.css
frontend/src/styles/Footer.css
frontend/src/styles/Header.css
frontend/src/styles/index.css
frontend/tailwind.config.ts
frontend/tsconfig.eslint.json

Adds responsive styling to the ReadingPage

Mobile reading page

---

frontend/src/assets/INKPROV Privacy Policy.rtf
frontend/src/components/pages/PrivacyPage.tsx
frontend/src/components/routing/router.tsx

fix: adds privacy and content

---

frontend/src/components/navigation_pages/LandingPage.tsx

Landing Page is now fully responsive on all types of screens

styling: Landing page mobile responsive

---

frontend/src/utils/supabase.tsx

adds a few more genre-themed user avatars

feat: add additional user avatar options

---

README.md
frontend/src/components/ProjectCard.tsx
frontend/src/components/navigation_pages/ProjectsPage.tsx
frontend/src/components/routing/router.tsx
frontend/src/utils/supabase.tsx

adds loading skeletons to Stories page for uniformity with Sessions page
minor changes to sort and search presentation 
@takeyasu-g handled mobile responsiveness and may wish to check Stories page for proper display before merging

Adds loading skeletons to stories

---

frontend/src/components/navigation_pages/LandingPage.tsx
frontend/src/components/navigation_pages/ProjectsPage.tsx
frontend/src/components/navigation_pages/Settings.tsx
frontend/src/components/writing_pages/CreateSessionPage.tsx
frontend/src/utils/supabase.tsx

- added logic to Sessions and Stories pages to check against already-existing users_ext.user_profile_mature_enabled flag
-- database nomenclature needs a cleanup which will cascade into codebase refactoring demands

Fixes mature content filtering

---

backend/package-lock.json
frontend/package-lock.json
frontend/package.json
frontend/src/components/GenreFilter.tsx
frontend/src/components/Header.tsx
frontend/src/components/auth/LoginPage.tsx
frontend/src/components/auth/RegisterPage.tsx
frontend/src/components/navigation_pages/Profile.tsx
frontend/src/components/navigation_pages/ProjectsPage.tsx
frontend/src/components/navigation_pages/ReadingPage.tsx
frontend/src/components/routing/router.tsx
frontend/src/components/ui/carousel.tsx
frontend/src/components/user/RewardTrophiesPage.tsx

Webapp should now be fully  mobile responsive and fixed minor bugs.
can be used on desktop, tablets and mobile on both portrait mode or landscape mode

Profile mobile responsiveness

---

frontend/src/components/navigation_pages/Settings.tsx
frontend/src/components/writing_pages/CreateSessionPage.tsx
frontend/src/components/writing_pages/WritingEditor.tsx

Fixed broken content moderation URL.
URL was incorrectly falling back to dev URL.
This fixes issue #73

fix: content moderation URL updated

---

frontend/src/components/Header.tsx
frontend/src/components/navigation_pages/Profile.tsx
frontend/src/components/writing_pages/CreateSessionPage.tsx
frontend/src/components/writing_pages/WritingEditor.tsx
frontend/src/hooks/useLocalStorage.tsx
frontend/src/types/global.d.ts

WritingPage/ CreateSessionsPage now have persistent entries. Used a custom hook so that no unnecessary re-renders happen and the initial page doesn't load null on useStates
refactored Header.tsx to not call supabase 4 times on refresh or on inital login load. now its just 1 call on load.

WritingPage/ Create SessionsPage entries persistent

---

frontend/src/components/auth/LoginPage.tsx
frontend/src/components/auth/RegisterPage.tsx
frontend/src/utils/formSchemas.ts

fix: the login and sign up pages use correct zod validation messages and doesn't cause error message when continuing with Google

PR: continue with Google no longer causes error message 

---

frontend/src/components/auth/RegisterPage.tsx
frontend/src/components/writing_pages/WritingEditor.tsx

Adds project completion models to WritingEntry - checks for total contributions,  checks on submit, and checks on new contributor attempting to join

feat: enhance project completion logic in WritingEditor component

---

frontend/src/components/Header.tsx
frontend/src/components/navigation_pages/Settings.tsx
frontend/src/components/routing/router.tsx
frontend/src/components/ui/CardHeaderWithMature.tsx
frontend/src/components/writing_pages/CreateSessionPage.tsx
frontend/src/components/writing_pages/WritingEditor.tsx

Render deploy fixes

---

frontend/src/components/ProfileSettings.tsx
frontend/src/components/navigation_pages/Settings.tsx
frontend/src/components/writing_pages/CreateSessionPage.tsx
frontend/src/components/writing_pages/WritingEditor.tsx

This Fixes the issue in production where users are experiencing a 404 error when attempting submit content through a text field.

fix: remove additional / in moderation URL

---

frontend/src/App.tsx
frontend/src/components/ContributorPopup.tsx
frontend/src/components/Header.tsx
frontend/src/components/ProfileSettings.tsx
frontend/src/components/UserSettings.tsx
frontend/src/components/navigation_pages/LandingPage.tsx
frontend/src/components/navigation_pages/Profile.tsx
frontend/src/components/navigation_pages/ReadingPage.tsx
frontend/src/components/routing/router.tsx
frontend/src/components/user/RewardTrophiesPage.tsx
frontend/src/utils/supabase.tsx

Now can access other users profile in the Reading Page + a bunch of other bugs , now properly inserts default achievements if they don't have any yet. (can look at the commits for all bugs)
tried to fix the users not logged in can view sessions page, but still can't make the view a session card to work, because the writingPage has a a lot of checks to use currentUser id to get sessions data.

View anyones profile

---

backend/server.js
backend/utils/contentModeration.js
frontend/src/App.tsx
frontend/src/components/ProfileSettings.tsx
frontend/src/components/writing_pages/CreateSessionPage.tsx
frontend/src/components/writing_pages/WritingEditor.tsx
frontend/src/locales/en.json
frontend/src/locales/ja.json

Improved Moderation to be less strict when the mature content has been toggled on. As well as correctly identify harmful language and display to user the main reason the content was flagged.

fix: moderation enhancement

---

frontend/src/App.tsx
frontend/src/components/ProjectCard.tsx
frontend/src/components/SessionCard.tsx
frontend/src/components/writing_pages/CreateSessionPage.tsx
frontend/src/components/writing_pages/WritingEditor.tsx
frontend/src/types/global.d.ts
frontend/src/utils/supabase.tsx

attempt to fix bugs in the writing and creating sessions , project_contributors not being visible

Bug fixes demo day
